### PR TITLE
Update DNA-Registry.csv

### PR DESCRIPTION
**Pull request by 0x3d5157636b525761**
Allocating numbers.

### CODE REVIEW

**Comment by trylinux** [comment]
Do you have a name we can associate with this block?

**Comment by 0x3d5157636b525761** [comment]
I'm a solitary security researcher, so I'd like to stay anonymous, at least
for now.
Is that okay?

**Comment by trylinux** [comment]
Not necessarily a problem at all! 
However, do you have some past work you could point us to? You can also email us that information to the email on the main page.

**Comment by 0x3d5157636b525761** [comment]
No, due to the nature of my work I don't have any.
However, I do have a (currently empty) blog with 3 posts that I intend to
release as soon as the respectable vendors fix the issues (I'll need two
"CVEs" to begin with).

**Comment by 0x3d5157636b525761** [comment]
...?

**Comment by kurtseifried** [comment]
What would probably work best is to request the 2 CVE's you need from us directly, if you turn out to be prolific then you can get a block no problem.

**Pull request merged**
